/** Stable Maestro selectors — never use translated UI strings in flows. */
export const TestIds = {
  tab: {
    inbox: 'tab.inbox',
    settings: 'tab.settings',
    record: 'tab.record',
  },
  onboarding: {
    skip: 'onboarding.skip',
    next: 'onboarding.next',
    getStarted: 'onboarding.getStarted',
    termsAgree: 'onboarding.terms.agree',
    termsNotNow: 'onboarding.terms.notNow',
    restoreBackup: 'onboarding.restoreBackup',
  },
  inbox: {
    screen: 'inbox.screen',
    emptyState: 'inbox.emptyState',
    search: 'inbox.search',
    firstRecord: 'inbox.firstRecord',
    recordCard: (id: string) => `inbox.recordCard.${id}`,
    menu: 'inbox.menu',
    batchSelect: 'inbox.batchSelect',
    allTasks: 'inbox.allTasks',
    swipeHintDismiss: 'inbox.swipeHintDismiss',
  },
  record: {
    start: 'record.start',
    pause: 'record.pause',
    stop: 'record.stop',
    mark: 'record.mark',
    close: 'record.close',
    timer: 'record.timer',
  },
  save: {
    titleInput: 'save.titleInput',
    meetingToggle: 'save.meetingToggle',
    confirm: 'save.confirm',
    discard: 'save.discard',
    cancel: 'save.cancel',
  },
  textNote: {
    screen: 'textNote.screen',
    titleInput: 'textNote.titleInput',
    body: 'textNote.body',
    save: 'textNote.save',
    close: 'textNote.close',
    template: (id: string) => `textNote.template.${id}`,
  },
  detail: {
    screen: 'detail.screen',
    tab: {
      transcript: 'detail.tab.transcript',
      summary: 'detail.tab.summary',
      tasks: 'detail.tab.tasks',
      dialogue: 'detail.tab.dialogue',
    },
    back: 'detail.back',
    addTask: 'detail.addTask',
    share: 'detail.share',
    askAi: 'detail.askAi',
  },
  player: {
    playPause: 'player.playPause',
  },
  allTasks: {
    screen: 'allTasks.screen',
    create: 'allTasks.create',
    clearNoteFilter: 'allTasks.clearNoteFilter',
  },
  notesGraph: {
    screen: 'notesGraph.screen',
    export: 'notesGraph.export',
  },
  settings: {
    screen: 'settings.screen',
    appearance: 'settings.appearance',
    trash: 'settings.trash',
    import: 'settings.import',
    storageDetails: 'settings.storageDetails',
    whisperPicker: 'settings.whisperPicker',
    aiSettings: 'settings.aiSettings',
    appLockSetup: 'settings.appLockSetup',
    about: 'settings.about',
    digest: 'settings.digest',
    siriShortcuts: 'settings.siriShortcuts',
    debug: 'settings.debug',
  },
  trash: {
    screen: 'trash.screen',
    emptyTrash: 'trash.emptyTrash',
    restoreItem: (id: string) => `trash.restore.${id}`,
    deleteForeverItem: (id: string) => `trash.deleteForever.${id}`,
  },
  appLock: {
    screen: 'appLock.screen',
    pinInput: 'appLock.pinInput',
    biometric: 'appLock.biometric',
  },
  paywall: {
    sheet: 'paywall.sheet',
    dismiss: 'paywall.dismiss',
  },
  e2e: {
    ready: 'e2e.ready',
  },
} as const;
