approvedGitRepositories:
  - "**"

enableScripts: true

nmHoistingLimits: workspaces

nodeLinker: node-modules

supportedArchitectures:
  os:
    - current
    - linux
  cpu:
    - current
    - x64
  libc:
    - current
    - glibc

npmMinimalAgeGate: 0

npmRegistryServer: "https://registry.npmjs.org"

yarnPath: .yarn/releases/yarn-4.17.0.cjs
