export {
  REMOTE_SYNC_AI_SETTINGS_FILE as ICLOUD_SYNC_AI_SETTINGS_FILE,
  REMOTE_SYNC_COOLDOWN_MS as ICLOUD_SYNC_COOLDOWN_MS,
  REMOTE_SYNC_DEFAULT_BASE_PATH as ICLOUD_SYNC_DEFAULT_BASE_PATH,
  REMOTE_SYNC_DEFAULT_REPO_NAME as ICLOUD_SYNC_DEFAULT_REPO_NAME,
  REMOTE_SYNC_HEAD_FILE as ICLOUD_SYNC_HEAD_FILE,
  REMOTE_SYNC_HEAD_FORMAT_VERSION as ICLOUD_SYNC_HEAD_FORMAT_VERSION,
  REMOTE_SYNC_LEGACY_MANIFEST_FILE as ICLOUD_SYNC_LEGACY_MANIFEST_FILE,
  REMOTE_SYNC_MANIFEST_FILE as ICLOUD_SYNC_MANIFEST_FILE,
  REMOTE_SYNC_NOTES_DIR as ICLOUD_SYNC_NOTES_DIR,
  REMOTE_SYNC_PRIVATE_REMOTE_PROFILES_FILE as ICLOUD_SYNC_PRIVATE_REMOTE_PROFILES_FILE,
  REMOTE_SYNC_README_FILE as ICLOUD_SYNC_README_FILE,
  REMOTE_SYNC_STRUCTURE_VERSION as ICLOUD_SYNC_STRUCTURE_VERSION,
  REMOTE_SYNC_TIMEOUT_MS as ICLOUD_SYNC_TIMEOUT_MS,
} from '@/features/git-remote-sync/lib/constants';

export const ICLOUD_SYNC_VERSIONS_DIR = '.voice-inbox-ai/versions';
export const ICLOUD_SYNC_VERSION_META_FILE = 'version-meta.json';
export const ICLOUD_SYNC_MAX_VERSIONS = 50;
