/**
 * Drizzle migrations config for useMigrations/migrate().
 * Generated by drizzle-kit, journal from drizzle/meta/_journal.json
 */
import journal from '../../../../drizzle/meta/_journal.json';

const migration0000 = `CREATE TABLE IF NOT EXISTS \`records\` (
	\`id\` text PRIMARY KEY NOT NULL,
	\`title\` text NOT NULL,
	\`transcript\` text DEFAULT '',
	\`transcriptSegments\` text DEFAULT '[]',
	\`summary\` text DEFAULT '',
	\`tasks\` text DEFAULT '[]',
	\`duration\` text DEFAULT '0:00',
	\`createdAt\` text DEFAULT '',
	\`relativeTime\` text DEFAULT '',
	\`status\` text DEFAULT 'unread',
	\`aiStatus\` text DEFAULT 'idle',
	\`transcriptProgress\` integer DEFAULT 0,
	\`isPinned\` integer DEFAULT 0,
	\`tags\` text DEFAULT '[]',
	\`audioPath\` text
);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS \`idx_records_isPinned\` ON \`records\` (\`isPinned\`);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS \`idx_records_createdAt\` ON \`records\` (\`createdAt\`);`;

const migration0001 = `ALTER TABLE \`records\` ADD \`durationMs\` integer DEFAULT 0;`;

const migration0002 = `SELECT 1;`;

export const migrationsConfig = {
  journal: {
    entries: journal.entries.map((e) => ({
      idx: e.idx,
      when: e.when,
      tag: e.tag,
      breakpoints: e.breakpoints ?? true,
    })),
  },
  migrations: {
    m0000: migration0000,
    m0001: migration0001,
    m0002: migration0002,
  } as Record<string, string>,
};
