/**
 * Drizzle migrations config for useMigrations/migrate().
 * Generated by drizzle-kit, journal from drizzle/meta/_journal.json
 */
import journal from '../../../../drizzle/meta/_journal.json';

const migration0000 = `CREATE TABLE IF NOT EXISTS \`records\` (
	\`id\` text PRIMARY KEY NOT NULL,
	\`title\` text NOT NULL,
	\`transcript\` text DEFAULT '',
	\`transcriptSegments\` text DEFAULT '[]',
	\`summary\` text DEFAULT '',
	\`tasks\` text DEFAULT '[]',
	\`duration\` text DEFAULT '0:00',
	\`createdAt\` text DEFAULT '',
	\`relativeTime\` text DEFAULT '',
	\`status\` text DEFAULT 'unread',
	\`aiStatus\` text DEFAULT 'idle',
	\`transcriptProgress\` integer DEFAULT 0,
	\`isPinned\` integer DEFAULT 0,
	\`tags\` text DEFAULT '[]',
	\`audioPath\` text
);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS \`idx_records_isPinned\` ON \`records\` (\`isPinned\`);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS \`idx_records_createdAt\` ON \`records\` (\`createdAt\`);`;

const migration0001 = `ALTER TABLE \`records\` ADD \`durationMs\` integer DEFAULT 0;`;

const migration0002 = `SELECT 1;`;

const migration0003 = `ALTER TABLE \`records\` ADD \`classification\` text;--> statement-breakpoint
ALTER TABLE \`records\` ADD \`keyPhrases\` text DEFAULT '[]';--> statement-breakpoint
ALTER TABLE \`records\` ADD \`nextSteps\` text DEFAULT '[]';`;

const migration0004 = `ALTER TABLE \`records\` ADD \`translatedTranscript\` text;--> statement-breakpoint
ALTER TABLE \`records\` ADD \`translationLanguage\` text;`;

const migration0005 = `ALTER TABLE \`records\` ADD \`embedding\` text;`;

const migration0006 = `CREATE TABLE IF NOT EXISTS \`folders\` (
\`id\` text PRIMARY KEY NOT NULL,
\`name\` text NOT NULL,
\`color\` text DEFAULT '#6b7280',
\`icon\` text DEFAULT '📁',
\`sortOrder\` integer DEFAULT 0,
\`createdAt\` text NOT NULL
);
--> statement-breakpoint
ALTER TABLE \`records\` ADD \`folderId\` text;
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS \`idx_records_folderId\` ON \`records\` (\`folderId\`);`;

const migration0007 = `ALTER TABLE \`records\` ADD \`readAt\` text;--> statement-breakpoint
UPDATE \`records\` SET \`readAt\` = \`createdAt\` WHERE \`status\` = 'read' AND (\`readAt\` IS NULL OR \`readAt\` = '');`;

const migration0008 = `CREATE TABLE IF NOT EXISTS \`record_ask_ai\` (
	\`recordId\` text PRIMARY KEY NOT NULL,
	\`payload\` text NOT NULL,
	\`updatedAt\` text NOT NULL
);`;

const migration0009 = `ALTER TABLE \`records\` ADD \`deletedAt\` text;--> statement-breakpoint
ALTER TABLE \`records\` ADD \`purgeAt\` text;--> statement-breakpoint
CREATE INDEX \`idx_records_purgeAt\` ON \`records\` (\`purgeAt\`);`;

const migration0010 = `ALTER TABLE \`records\` ADD \`recordingMarks\` text DEFAULT '[]';`;

const migration0011 = `ALTER TABLE \`records\` ADD \`meetingDialogue\` text;`;

const migration0012 = `ALTER TABLE \`records\` ADD \`summaryReasoning\` text;`;

const migration0013 = `ALTER TABLE \`records\` ADD \`summaryAiModel\` text;`;

const migration0014 = `ALTER TABLE \`records\` ADD \`summaryTokensPrompt\` integer;--> statement-breakpoint
ALTER TABLE \`records\` ADD \`summaryTokensCompletion\` integer;`;

const migration0015 = `ALTER TABLE \`records\` ADD \`summaryGenerationMs\` integer;`;

const migration0016 = `CREATE TABLE IF NOT EXISTS \`cloud_ai_pending\` (
	\`recordId\` text PRIMARY KEY NOT NULL,
	\`jobId\` text NOT NULL,
	\`syncToken\` text,
	\`expectAsyncMeetingDialogue\` integer DEFAULT 0 NOT NULL,
	\`expiresAtMs\` integer NOT NULL,
	\`updatedAt\` text NOT NULL
);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS \`idx_cloud_ai_pending_jobId\` ON \`cloud_ai_pending\` (\`jobId\`);`;

const migration0017 = `ALTER TABLE \`records\` ADD \`meetingSpeakerLabels\` text;--> statement-breakpoint
ALTER TABLE \`records\` ADD \`cloudAiJobId\` text;`;

const migration0018 = `ALTER TABLE \`records\` ADD \`summaryAiModelLabel\` text;`;

const migration0019 = `ALTER TABLE \`records\` ADD \`meetingSummaryTemplate\` text;`;

const migration0020 = `CREATE TABLE IF NOT EXISTS \`notes_graph_layout_version\` (
	\`id\` text PRIMARY KEY NOT NULL,
	\`layoutKey\` text NOT NULL,
	\`versionNumber\` integer NOT NULL,
	\`payload\` text NOT NULL,
	\`createdAt\` text NOT NULL
);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS \`idx_notes_graph_layout_key\` ON \`notes_graph_layout_version\` (\`layoutKey\`);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS \`idx_notes_graph_layout_created\` ON \`notes_graph_layout_version\` (\`createdAt\`);`;

const migration0021 = `ALTER TABLE \`notes_graph_layout_version\` ADD \`name\` text;`;

const migration0022 = `CREATE TABLE IF NOT EXISTS \`private_ai_task_queue\` (
	\`id\` text PRIMARY KEY NOT NULL,
	\`recordId\` text NOT NULL,
	\`taskType\` text NOT NULL,
	\`source\` text NOT NULL,
	\`attemptCount\` integer DEFAULT 0 NOT NULL,
	\`lastError\` text,
	\`createdAt\` text NOT NULL,
	\`updatedAt\` text NOT NULL
);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS \`idx_private_ai_task_queue_recordId\` ON \`private_ai_task_queue\` (\`recordId\`);
--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS \`idx_private_ai_task_queue_record_task\` ON \`private_ai_task_queue\` (\`recordId\`,\`taskType\`);`;

const migration0023 = `ALTER TABLE \`records\` ADD \`linkedRecordIds\` text DEFAULT '[]';`;

const migration0024 = `CREATE TABLE IF NOT EXISTS \`record_published_share\` (
	\`recordId\` text PRIMARY KEY NOT NULL,
	\`shareToken\` text NOT NULL,
	\`shareUrl\` text NOT NULL,
	\`template\` text NOT NULL,
	\`contentHash\` text NOT NULL,
	\`publishedAt\` text NOT NULL,
	\`expiresAt\` text,
	\`updatedAt\` text NOT NULL
);
--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS \`idx_record_published_share_token\` ON \`record_published_share\` (\`shareToken\`);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS \`idx_record_published_share_expires\` ON \`record_published_share\` (\`expiresAt\`);`;

const migration0025 = `ALTER TABLE \`records\` ADD \`summaryAiModelMode\` text;`;

export const migrationsConfig = {
  journal: {
    entries: journal.entries.map((e) => ({
      idx: e.idx,
      when: e.when,
      tag: e.tag,
      breakpoints: e.breakpoints ?? true,
    })),
  },
  migrations: {
    m0000: migration0000,
    m0001: migration0001,
    m0002: migration0002,
    m0003: migration0003,
    m0004: migration0004,
    m0005: migration0005,
    m0006: migration0006,
    m0007: migration0007,
    m0008: migration0008,
    m0009: migration0009,
    m0010: migration0010,
    m0011: migration0011,
    m0012: migration0012,
    m0013: migration0013,
    m0014: migration0014,
    m0015: migration0015,
    m0016: migration0016,
    m0017: migration0017,
    m0018: migration0018,
    m0019: migration0019,
    m0020: migration0020,
    m0021: migration0021,
    m0022: migration0022,
    m0023: migration0023,
    m0024: migration0024,
    m0025: migration0025,
  } as Record<string, string>,
};
