export const GRAPH_NODE_DOT_SIZE = 20;
export const GRAPH_NODE_DOT_SIZE_ACTIVE = 28;
export const GRAPH_NODE_DOT_SIZE_NEIGHBOR = 24;
export const GRAPH_NODE_DOT_CONTAINER_SIZE = GRAPH_NODE_DOT_SIZE_ACTIVE + 12;
export const GRAPH_NODE_DOT_LABEL_GAP = 3;
export const GRAPH_NODE_DOT_LABEL_MAX_WIDTH = 104;
export const GRAPH_NODE_DOT_LABEL_FONT_SIZE = 11;
