import type { AIModel, WhisperModel } from './types';

export const AI_MODELS: AIModel[] = [
  {
    id: 'gpt-4o',
    name: 'GPT-4o',
    provider: 'OpenAI',
    description: 'Самая мощная модель OpenAI с поддержкой мультимодального ввода',
    contextWindow: '128K токенов',
    speed: 'medium',
  },
  {
    id: 'gpt-4o-mini',
    name: 'GPT-4o mini',
    provider: 'OpenAI',
    description: 'Быстрая и экономичная модель для большинства задач',
    contextWindow: '128K токенов',
    speed: 'fast',
  },
  {
    id: 'claude-3-5-sonnet',
    name: 'Claude 3.5 Sonnet',
    provider: 'Anthropic',
    description: 'Оптимальный баланс между интеллектом и скоростью',
    contextWindow: '200K токенов',
    speed: 'medium',
  },
  {
    id: 'claude-3-haiku',
    name: 'Claude 3 Haiku',
    provider: 'Anthropic',
    description: 'Самая быстрая модель Anthropic для простых задач',
    contextWindow: '200K токенов',
    speed: 'fast',
  },
  {
    id: 'gemini-1-5-pro',
    name: 'Gemini 1.5 Pro',
    provider: 'Google',
    description: 'Мощная модель Google с огромным контекстным окном',
    contextWindow: '1M токенов',
    speed: 'slow',
  },
  {
    id: 'gemini-1-5-flash',
    name: 'Gemini 1.5 Flash',
    provider: 'Google',
    description: 'Быстрая и эффективная модель для повседневных задач',
    contextWindow: '1M токенов',
    speed: 'fast',
  },
];

export const WHISPER_MODELS: WhisperModel[] = [
  {
    id: 'whisper-tiny',
    name: 'Tiny',
    description: 'Минимальные требования к памяти, базовое качество',
    sizeLabel: '75 МБ',
    sizeMb: 75,
    accuracy: 'low',
    speed: 'fast',
    status: 'not_downloaded',
  },
  {
    id: 'whisper-base',
    name: 'Base',
    description: 'Хороший баланс между скоростью и качеством',
    sizeLabel: '145 МБ',
    sizeMb: 145,
    accuracy: 'medium',
    speed: 'fast',
    status: 'not_downloaded',
  },
  {
    id: 'whisper-small',
    name: 'Small',
    description: 'Улучшенное качество для большинства языков',
    sizeLabel: '466 МБ',
    sizeMb: 466,
    accuracy: 'medium',
    speed: 'medium',
    status: 'not_downloaded',
  },
  {
    id: 'whisper-medium',
    name: 'Medium',
    description: 'Высокое качество транскрипции',
    sizeLabel: '1.5 ГБ',
    sizeMb: 1500,
    accuracy: 'high',
    speed: 'slow',
    status: 'not_downloaded',
  },
  {
    id: 'whisper-large-v3',
    name: 'Large v3',
    description: 'Максимальное качество, поддержка 99 языков',
    sizeLabel: '3.1 ГБ',
    sizeMb: 3100,
    accuracy: 'very_high',
    speed: 'very_slow',
    status: 'not_downloaded',
  },
];
