///
/// NitroFSOnLoad.cpp
/// Vendored for react-native-nitro-modules 0.35+ (CxxPart registration + JavaClass factory).
/// Upstream 0.8.2 uses DefaultConstructableObject + old JHybrid shape; see patch-nitro-fs-android-nitro035.mjs.
///

#ifndef BUILDING_NITROFS_WITH_GENERATED_CMAKE_PROJECT
#error NitroFSOnLoad.cpp is not being built with the autogenerated CMakeLists.txt project. Is a different CMakeLists.txt building this?
#endif

#include "NitroFSOnLoad.hpp"

#include <jni.h>
#include <fbjni/fbjni.h>
#include <NitroModules/HybridObjectRegistry.hpp>

#include "JHybridNitroFSSpec.hpp"
#include "JFunc_void_double_double.hpp"

namespace margelo::nitro::nitrofs {

struct JHybridNitroFSImpl : public jni::JavaClass<JHybridNitroFSImpl, JHybridNitroFSSpec::JavaPart> {
  static auto constexpr kJavaDescriptor = "Lcom/nitrofs/HybridNitroFS;";
  static std::shared_ptr<JHybridNitroFSSpec> create() {
    static auto constructorFn = javaClassStatic()->getConstructor<JHybridNitroFSImpl::javaobject()>();
    jni::local_ref<JHybridNitroFSSpec::JavaPart> javaPart = javaClassStatic()->newObject(constructorFn);
    return javaPart->getJHybridNitroFSSpec();
  }
};

int initialize(JavaVM* vm) {
  return facebook::jni::initialize(vm, []() {
    using namespace margelo::nitro;

    margelo::nitro::nitrofs::JFunc_void_double_double_cxx::registerNatives();
    margelo::nitro::nitrofs::JHybridNitroFSSpec::CxxPart::registerNatives();

    HybridObjectRegistry::registerHybridObjectConstructor(
        "NitroFS",
        []() -> std::shared_ptr<HybridObject> { return JHybridNitroFSImpl::create(); });
  });
}

} // namespace margelo::nitro::nitrofs
