export {
  REMOTE_SYNC_DEFAULT_BRANCH as GITLAB_SYNC_DEFAULT_BRANCH,
  REMOTE_SYNC_DEFAULT_REPO_NAME as GITLAB_SYNC_DEFAULT_REPO_NAME,
  REMOTE_SYNC_DEFAULT_BASE_PATH as GITLAB_SYNC_DEFAULT_BASE_PATH,
  REMOTE_SYNC_LEGACY_MANIFEST_FILE as GITLAB_SYNC_LEGACY_MANIFEST_FILE,
  REMOTE_SYNC_MANIFEST_FILE as GITLAB_SYNC_MANIFEST_FILE,
  REMOTE_SYNC_HEAD_FILE as GITLAB_SYNC_HEAD_FILE,
  REMOTE_SYNC_NOTES_DIR as GITLAB_SYNC_NOTES_DIR,
  REMOTE_SYNC_README_FILE as GITLAB_SYNC_README_FILE,
  REMOTE_SYNC_HEAD_FORMAT_VERSION as GITLAB_HEAD_FORMAT_VERSION,
  REMOTE_SYNC_STRUCTURE_VERSION as GITLAB_SYNC_STRUCTURE_VERSION,
  REMOTE_SYNC_FETCH_TIMEOUT_MS as GITLAB_FETCH_TIMEOUT_MS,
  REMOTE_SYNC_FETCH_MAX_RETRIES as GITLAB_FETCH_MAX_RETRIES,
  REMOTE_SYNC_FETCH_RETRY_BASE_MS as GITLAB_FETCH_RETRY_BASE_MS,
  REMOTE_SYNC_REF_CONFLICT_MAX_RETRIES as GITLAB_REF_CONFLICT_MAX_RETRIES,
  REMOTE_SYNC_TIMEOUT_MS as GITLAB_SYNC_TIMEOUT_MS,
  REMOTE_SYNC_COOLDOWN_MS as GITLAB_SYNC_COOLDOWN_MS,
} from '@/features/git-remote-sync/lib/constants';

export const GITLAB_OAUTH_SCOPE = 'api read_user write_repository';
export const GITLAB_API_BASE = 'https://gitlab.com/api/v4';
export const GITLAB_DEVICE_CODE_URL = 'https://gitlab.com/oauth/authorize_device';
export const GITLAB_ACCESS_TOKEN_URL = 'https://gitlab.com/oauth/token';
