-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgjQUxeqJB3yF1prg8
Htq1n+A+md/1IuKrjG3deVNYGYCgCgYIKoZIzj0DAQehRANCAAQRzXHq7FB3Kbqv
QE8VNlqgW+NhAUeqiYMlsduDyJAWW0I7V9WzdyyPPaeUsCgT7rhJt/nuGVQ/WQbR
0kDG2QHB
-----END PRIVATE KEY-----